ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.xentoryxlabs.MainKt.module

redis:
  host: "127.0.0.1"
  port: 6379

db:
  mongo:
    host: "127.0.0.1"
    port: 27017
    database:
      name: "myDatabase"


